import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import '/app/globals.css'
import { currentUser } from '@clerk/nextjs/server'
import { permanentRedirect } from 'next/navigation'
import NavLinksAdmin from '@/components/navlinksadmin'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await currentUser();
  const userid = user?.id;

  if (!user) {
    permanentRedirect('/')
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SignedIn>
            {/* Container */}
            <div className='flex flex-row w-full min-h-screen'>
              {/* Navbar */}
              <div className='peer fixed z-9999'>
                <NavLinksAdmin />
              </div>

              {/* Page Content */}
              <div className='w-full ml-13 peer-hover:pl-48 transition-all duration-500'>
                <div className='flex flex-wrap gap-2 p-5'>
                  {children}
                </div>
              </div>

              <div className='fixed bg-black z-2 w-screen h-screen opacity-0 hidden peer-hover:opacity-20 peer-hover:block transition-opacity duration-1000'/>
            </div>
            
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}