import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Space_Grotesk, Inter } from "next/font/google";
import "/app/globals.css";
import { currentUser } from "@clerk/nextjs/server";
import { permanentRedirect } from "next/navigation";
import NavLinksAdmin from "@/components/admin/navlinksadmin";
import Link from "next/link";
import { InfoIcon, User } from "lucide-react";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Analytics } from "@vercel/analytics/next";
import AdminAlerts from "@/components/admin/alerts";
import { Button } from "@headlessui/react";
import AlertFragment from "@/components/admin/alert-fragment";

const spaceGrotesk = Space_Grotesk({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const inter = Inter({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Chronicles",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userid = user?.id;

  if (!user) {
    permanentRedirect("/");
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${spaceGrotesk.className} ${inter.className}`}>
          <div className="fixed right-4 bottom-4 z-20 flex w-90 flex-col items-end gap-2">
            {/* ALERTS */}
            <AlertFragment />

            {/* Back to User Home */}
            <Link
              href={"/"}
              className="hover:bg-neutral-full w-fit rounded-full bg-neutral-100 p-4 text-black hover:cursor-pointer"
            >
              <User />
            </Link>
          </div>

          <SignedIn>
            {/* Container */}
            <div className="flex min-h-screen w-full flex-row bg-black/30">
              {/* Navbar */}
              <div className="peer fixed z-9999">
                <NavLinksAdmin />
              </div>

              {/* Page Content */}
              <div className="ml-13 w-full transition-all duration-500 peer-hover:pl-48">
                <div className="flex min-h-full flex-wrap gap-2 p-5">
                  <NuqsAdapter>{children}</NuqsAdapter>
                  <SpeedInsights />
                  <Analytics />
                </div>
              </div>

              <div className="fixed z-2 hidden h-screen w-screen bg-black opacity-0 transition-opacity duration-1000 peer-hover:block peer-hover:opacity-20" />
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
