import type { Metadata } from "next";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "/app/globals.css";
import { currentUser } from "@clerk/nextjs/server";
import { permanentRedirect } from "next/navigation";
import NavLinksAdmin from "@/components/admin/navlinksadmin";
import Link from "next/link";
import { User } from "lucide-react";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chronicles",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userid = user?.id;

  if (!user) {
    permanentRedirect("/");
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Link
            href={"/"}
            className="fixed right-4 bottom-4 z-20 rounded-full bg-neutral-100 p-4 text-black hover:cursor-pointer hover:bg-neutral-200"
          >
            <User />
          </Link>
          <SignedIn>
            {/* Container */}
            <div className="flex min-h-screen w-full flex-row bg-black/30">
              {/* Navbar */}
              <div className="peer fixed z-9999">
                <NavLinksAdmin />
              </div>

              {/* Page Content */}
              <div className="ml-13 w-full transition-all duration-500 peer-hover:pl-48">
                <div className="flex min-h-full flex-wrap gap-2 p-5">
                  <NuqsAdapter>{children}</NuqsAdapter>
                </div>
              </div>

              <div className="fixed z-2 hidden h-screen w-screen bg-black opacity-0 transition-opacity duration-1000 peer-hover:block peer-hover:opacity-20" />
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
